// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: zwift.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ZwiftClassLibrary {

  /// <summary>Holder for reflection information generated from zwift.proto</summary>
  public static partial class ZwiftReflection {

    #region Descriptor
    /// <summary>File descriptor for zwift.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ZwiftReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cgt6d2lmdC5wcm90bxIRWndpZnRDbGFzc0xpYnJhcnki1AYKC1BsYXllclN0",
            "YXRlEhEKCWF0aGxldGVJZBgBIAEoBRIRCgl3b3JsZFRpbWUYAiABKAQSEAoI",
            "ZGlzdGFuY2UYAyABKAUSEAoIcm9hZFRpbWUYBCABKAUSDAoEbGFwcxgFIAEo",
            "BRIOCgZfc3BlZWQYBiABKAUSFAoMcm9hZFBvc2l0aW9uGAggASgFEhMKC19j",
            "YWRlbmNlVUh6GAkgASgFEg0KBWRyYWZ0GAogASgFEhEKCWhlYXJ0cmF0ZRgL",
            "IAEoBRINCgVwb3dlchgMIAEoBRIQCghfaGVhZGluZxgNIAEoBRIMCgRsZWFu",
            "GA4gASgFEhAKCGNsaW1iaW5nGA8gASgFEgwKBHRpbWUYECABKAUSEAoIZnJh",
            "bWVIdWUYEiABKA0SDwoHX2ZsYWdzMRgTIAEoDRIPCgdfZmxhZ3MyGBQgASgN",
            "EhEKCV9wcm9ncmVzcxgVIAEoDRIRCglfam9pblRpbWUYFiABKAMSFAoManVz",
            "dFdhdGNoaW5nGBcgASgIEhAKCF9td0hvdXJzGBggASgFEgkKAXgYGSABKAIS",
            "CQoBehgaIAEoAhIJCgF5GBsgASgCEhkKEXdhdGNoaW5nQXRobGV0ZUlkGBwg",
            "ASgFEhcKD2V2ZW50U3ViZ3JvdXBJZBgdIAEoBRInCgVzcG9ydBgfIAEoDjIY",
            "Llp3aWZ0Q2xhc3NMaWJyYXJ5LlNwb3J0EhYKDl9ldmVudERpc3RhbmNlGCIg",
            "ASgCEhAKCGNvdXJzZUlkGCMgASgFEhUKDXJvdXRlUHJvZ3Jlc3MYJCABKAUS",
            "FgoOcm91dGVSb2FkSW5kZXgYJSABKAUSEAoIY2FuU3RlZXIYJiABKAgSDwoH",
            "cm91dGVJZBgnIAEoDRIZChFwYWNlckJvdEdyb3VwU2l6ZRgoIAEoBRITCgth",
            "Y3RpdmVTdGVlchgpIAEoCBIOCgZwb3J0YWwYKyABKAgSGwoTcG9ydGFsR3Jh",
            "ZGllbnRTY2FsZRgsIAEoBRIcChRwb3J0YWxFbGV2YXRpb25TY2FsZRgtIAEo",
            "BRIQCghib29zdFBhZBguIAEoBRIRCgloYXphcmRQYWQYLyABKAUSEQoJdGlt",
            "ZUJvbnVzGDAgASgFEhIKCnJpZGVvbkJvbWIYMSABKAUqRQoFU3BvcnQSCwoH",
            "Y3ljbGluZxAAEgsKB3J1bm5pbmcQARIKCgZyb3dpbmcQAhIKCgZzcG9ydDMQ",
            "AxIKCgZzcG9ydDQQBGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::ZwiftClassLibrary.Sport), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ZwiftClassLibrary.PlayerState), global::ZwiftClassLibrary.PlayerState.Parser, new[]{ "AthleteId", "WorldTime", "Distance", "RoadTime", "Laps", "Speed", "RoadPosition", "CadenceUHz", "Draft", "Heartrate", "Power", "Heading", "Lean", "Climbing", "Time", "FrameHue", "Flags1", "Flags2", "Progress", "JoinTime", "JustWatching", "MwHours", "X", "Z", "Y", "WatchingAthleteId", "EventSubgroupId", "Sport", "EventDistance", "CourseId", "RouteProgress", "RouteRoadIndex", "CanSteer", "RouteId", "PacerBotGroupSize", "ActiveSteer", "Portal", "PortalGradientScale", "PortalElevationScale", "BoostPad", "HazardPad", "TimeBonus", "RideonBomb" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum Sport {
    [pbr::OriginalName("cycling")] Cycling = 0,
    [pbr::OriginalName("running")] Running = 1,
    [pbr::OriginalName("rowing")] Rowing = 2,
    [pbr::OriginalName("sport3")] _3 = 3,
    [pbr::OriginalName("sport4")] _4 = 4,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PlayerState : pb::IMessage<PlayerState>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PlayerState> _parser = new pb::MessageParser<PlayerState>(() => new PlayerState());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PlayerState> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ZwiftClassLibrary.ZwiftReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerState() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerState(PlayerState other) : this() {
      athleteId_ = other.athleteId_;
      worldTime_ = other.worldTime_;
      distance_ = other.distance_;
      roadTime_ = other.roadTime_;
      laps_ = other.laps_;
      Speed_ = other.Speed_;
      roadPosition_ = other.roadPosition_;
      CadenceUHz_ = other.CadenceUHz_;
      draft_ = other.draft_;
      heartrate_ = other.heartrate_;
      power_ = other.power_;
      Heading_ = other.Heading_;
      lean_ = other.lean_;
      climbing_ = other.climbing_;
      time_ = other.time_;
      frameHue_ = other.frameHue_;
      Flags1_ = other.Flags1_;
      Flags2_ = other.Flags2_;
      Progress_ = other.Progress_;
      JoinTime_ = other.JoinTime_;
      justWatching_ = other.justWatching_;
      MwHours_ = other.MwHours_;
      x_ = other.x_;
      z_ = other.z_;
      y_ = other.y_;
      watchingAthleteId_ = other.watchingAthleteId_;
      eventSubgroupId_ = other.eventSubgroupId_;
      sport_ = other.sport_;
      EventDistance_ = other.EventDistance_;
      courseId_ = other.courseId_;
      routeProgress_ = other.routeProgress_;
      routeRoadIndex_ = other.routeRoadIndex_;
      canSteer_ = other.canSteer_;
      routeId_ = other.routeId_;
      pacerBotGroupSize_ = other.pacerBotGroupSize_;
      activeSteer_ = other.activeSteer_;
      portal_ = other.portal_;
      portalGradientScale_ = other.portalGradientScale_;
      portalElevationScale_ = other.portalElevationScale_;
      boostPad_ = other.boostPad_;
      hazardPad_ = other.hazardPad_;
      timeBonus_ = other.timeBonus_;
      rideonBomb_ = other.rideonBomb_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerState Clone() {
      return new PlayerState(this);
    }

    /// <summary>Field number for the "athleteId" field.</summary>
    public const int AthleteIdFieldNumber = 1;
    private int athleteId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int AthleteId {
      get { return athleteId_; }
      set {
        athleteId_ = value;
      }
    }

    /// <summary>Field number for the "worldTime" field.</summary>
    public const int WorldTimeFieldNumber = 2;
    private ulong worldTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong WorldTime {
      get { return worldTime_; }
      set {
        worldTime_ = value;
      }
    }

    /// <summary>Field number for the "distance" field.</summary>
    public const int DistanceFieldNumber = 3;
    private int distance_;
    /// <summary>
    /// meters
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Distance {
      get { return distance_; }
      set {
        distance_ = value;
      }
    }

    /// <summary>Field number for the "roadTime" field.</summary>
    public const int RoadTimeFieldNumber = 4;
    private int roadTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int RoadTime {
      get { return roadTime_; }
      set {
        roadTime_ = value;
      }
    }

    /// <summary>Field number for the "laps" field.</summary>
    public const int LapsFieldNumber = 5;
    private int laps_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Laps {
      get { return laps_; }
      set {
        laps_ = value;
      }
    }

    /// <summary>Field number for the "_speed" field.</summary>
    public const int SpeedFieldNumber = 6;
    private int Speed_;
    /// <summary>
    /// mm / hour
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Speed {
      get { return Speed_; }
      set {
        Speed_ = value;
      }
    }

    /// <summary>Field number for the "roadPosition" field.</summary>
    public const int RoadPositionFieldNumber = 8;
    private int roadPosition_;
    /// <summary>
    /// Horiz, i.e. lane.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int RoadPosition {
      get { return roadPosition_; }
      set {
        roadPosition_ = value;
      }
    }

    /// <summary>Field number for the "_cadenceUHz" field.</summary>
    public const int CadenceUHzFieldNumber = 9;
    private int CadenceUHz_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CadenceUHz {
      get { return CadenceUHz_; }
      set {
        CadenceUHz_ = value;
      }
    }

    /// <summary>Field number for the "draft" field.</summary>
    public const int DraftFieldNumber = 10;
    private int draft_;
    /// <summary>
    /// seems to be in percentage / algo factor
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Draft {
      get { return draft_; }
      set {
        draft_ = value;
      }
    }

    /// <summary>Field number for the "heartrate" field.</summary>
    public const int HeartrateFieldNumber = 11;
    private int heartrate_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Heartrate {
      get { return heartrate_; }
      set {
        heartrate_ = value;
      }
    }

    /// <summary>Field number for the "power" field.</summary>
    public const int PowerFieldNumber = 12;
    private int power_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Power {
      get { return power_; }
      set {
        power_ = value;
      }
    }

    /// <summary>Field number for the "_heading" field.</summary>
    public const int HeadingFieldNumber = 13;
    private int Heading_;
    /// <summary>
    /// microrads from -pi -> 3pi
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Heading {
      get { return Heading_; }
      set {
        Heading_ = value;
      }
    }

    /// <summary>Field number for the "lean" field.</summary>
    public const int LeanFieldNumber = 14;
    private int lean_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Lean {
      get { return lean_; }
      set {
        lean_ = value;
      }
    }

    /// <summary>Field number for the "climbing" field.</summary>
    public const int ClimbingFieldNumber = 15;
    private int climbing_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Climbing {
      get { return climbing_; }
      set {
        climbing_ = value;
      }
    }

    /// <summary>Field number for the "time" field.</summary>
    public const int TimeFieldNumber = 16;
    private int time_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Time {
      get { return time_; }
      set {
        time_ = value;
      }
    }

    /// <summary>Field number for the "frameHue" field.</summary>
    public const int FrameHueFieldNumber = 18;
    private uint frameHue_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint FrameHue {
      get { return frameHue_; }
      set {
        frameHue_ = value;
      }
    }

    /// <summary>Field number for the "_flags1" field.</summary>
    public const int Flags1FieldNumber = 19;
    private uint Flags1_;
    /// <summary>
    /// Packed with info parsed in user code
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Flags1 {
      get { return Flags1_; }
      set {
        Flags1_ = value;
      }
    }

    /// <summary>Field number for the "_flags2" field.</summary>
    public const int Flags2FieldNumber = 20;
    private uint Flags2_;
    /// <summary>
    /// Packed with info parsed in user code
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Flags2 {
      get { return Flags2_; }
      set {
        Flags2_ = value;
      }
    }

    /// <summary>Field number for the "_progress" field.</summary>
    public const int ProgressFieldNumber = 21;
    private uint Progress_;
    /// <summary>
    /// 16-32 are some sort of inverse mask when set, 8-16 is pct progress, 0 is workout
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Progress {
      get { return Progress_; }
      set {
        Progress_ = value;
      }
    }

    /// <summary>Field number for the "_joinTime" field.</summary>
    public const int JoinTimeFieldNumber = 22;
    private long JoinTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long JoinTime {
      get { return JoinTime_; }
      set {
        JoinTime_ = value;
      }
    }

    /// <summary>Field number for the "justWatching" field.</summary>
    public const int JustWatchingFieldNumber = 23;
    private bool justWatching_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool JustWatching {
      get { return justWatching_; }
      set {
        justWatching_ = value;
      }
    }

    /// <summary>Field number for the "_mwHours" field.</summary>
    public const int MwHoursFieldNumber = 24;
    private int MwHours_;
    /// <summary>
    /// milliwatt/hours of energy
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int MwHours {
      get { return MwHours_; }
      set {
        MwHours_ = value;
      }
    }

    /// <summary>Field number for the "x" field.</summary>
    public const int XFieldNumber = 25;
    private float x_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float X {
      get { return x_; }
      set {
        x_ = value;
      }
    }

    /// <summary>Field number for the "z" field.</summary>
    public const int ZFieldNumber = 26;
    private float z_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Z {
      get { return z_; }
      set {
        z_ = value;
      }
    }

    /// <summary>Field number for the "y" field.</summary>
    public const int YFieldNumber = 27;
    private float y_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Y {
      get { return y_; }
      set {
        y_ = value;
      }
    }

    /// <summary>Field number for the "watchingAthleteId" field.</summary>
    public const int WatchingAthleteIdFieldNumber = 28;
    private int watchingAthleteId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int WatchingAthleteId {
      get { return watchingAthleteId_; }
      set {
        watchingAthleteId_ = value;
      }
    }

    /// <summary>Field number for the "eventSubgroupId" field.</summary>
    public const int EventSubgroupIdFieldNumber = 29;
    private int eventSubgroupId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int EventSubgroupId {
      get { return eventSubgroupId_; }
      set {
        eventSubgroupId_ = value;
      }
    }

    /// <summary>Field number for the "sport" field.</summary>
    public const int SportFieldNumber = 31;
    private global::ZwiftClassLibrary.Sport sport_ = global::ZwiftClassLibrary.Sport.Cycling;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ZwiftClassLibrary.Sport Sport {
      get { return sport_; }
      set {
        sport_ = value;
      }
    }

    /// <summary>Field number for the "_eventDistance" field.</summary>
    public const int EventDistanceFieldNumber = 34;
    private float EventDistance_;
    /// <summary>
    /// cm
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float EventDistance {
      get { return EventDistance_; }
      set {
        EventDistance_ = value;
      }
    }

    /// <summary>Field number for the "courseId" field.</summary>
    public const int CourseIdFieldNumber = 35;
    private int courseId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CourseId {
      get { return courseId_; }
      set {
        courseId_ = value;
      }
    }

    /// <summary>Field number for the "routeProgress" field.</summary>
    public const int RouteProgressFieldNumber = 36;
    private int routeProgress_;
    /// <summary>
    /// Increments with route progress, but the scale is unclear
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int RouteProgress {
      get { return routeProgress_; }
      set {
        routeProgress_ = value;
      }
    }

    /// <summary>Field number for the "routeRoadIndex" field.</summary>
    public const int RouteRoadIndexFieldNumber = 37;
    private int routeRoadIndex_;
    /// <summary>
    /// Offset into the road segment of a route (very close to our route's road manifest indexes)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int RouteRoadIndex {
      get { return routeRoadIndex_; }
      set {
        routeRoadIndex_ = value;
      }
    }

    /// <summary>Field number for the "canSteer" field.</summary>
    public const int CanSteerFieldNumber = 38;
    private bool canSteer_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool CanSteer {
      get { return canSteer_; }
      set {
        canSteer_ = value;
      }
    }

    /// <summary>Field number for the "routeId" field.</summary>
    public const int RouteIdFieldNumber = 39;
    private uint routeId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint RouteId {
      get { return routeId_; }
      set {
        routeId_ = value;
      }
    }

    /// <summary>Field number for the "pacerBotGroupSize" field.</summary>
    public const int PacerBotGroupSizeFieldNumber = 40;
    private int pacerBotGroupSize_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int PacerBotGroupSize {
      get { return pacerBotGroupSize_; }
      set {
        pacerBotGroupSize_ = value;
      }
    }

    /// <summary>Field number for the "activeSteer" field.</summary>
    public const int ActiveSteerFieldNumber = 41;
    private bool activeSteer_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool ActiveSteer {
      get { return activeSteer_; }
      set {
        activeSteer_ = value;
      }
    }

    /// <summary>Field number for the "portal" field.</summary>
    public const int PortalFieldNumber = 43;
    private bool portal_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Portal {
      get { return portal_; }
      set {
        portal_ = value;
      }
    }

    /// <summary>Field number for the "portalGradientScale" field.</summary>
    public const int PortalGradientScaleFieldNumber = 44;
    private int portalGradientScale_;
    /// <summary>
    /// 0 = 50%, 1 = 75%, 2 = 100%, 3 = 125%
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int PortalGradientScale {
      get { return portalGradientScale_; }
      set {
        portalGradientScale_ = value;
      }
    }

    /// <summary>Field number for the "portalElevationScale" field.</summary>
    public const int PortalElevationScaleFieldNumber = 45;
    private int portalElevationScale_;
    /// <summary>
    /// 50, 75, 100 or 125
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int PortalElevationScale {
      get { return portalElevationScale_; }
      set {
        portalElevationScale_ = value;
      }
    }

    /// <summary>Field number for the "boostPad" field.</summary>
    public const int BoostPadFieldNumber = 46;
    private int boostPad_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int BoostPad {
      get { return boostPad_; }
      set {
        boostPad_ = value;
      }
    }

    /// <summary>Field number for the "hazardPad" field.</summary>
    public const int HazardPadFieldNumber = 47;
    private int hazardPad_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int HazardPad {
      get { return hazardPad_; }
      set {
        hazardPad_ = value;
      }
    }

    /// <summary>Field number for the "timeBonus" field.</summary>
    public const int TimeBonusFieldNumber = 48;
    private int timeBonus_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int TimeBonus {
      get { return timeBonus_; }
      set {
        timeBonus_ = value;
      }
    }

    /// <summary>Field number for the "rideonBomb" field.</summary>
    public const int RideonBombFieldNumber = 49;
    private int rideonBomb_;
    /// <summary>
    /// always seems to be x5 with value of 9
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int RideonBomb {
      get { return rideonBomb_; }
      set {
        rideonBomb_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PlayerState);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PlayerState other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AthleteId != other.AthleteId) return false;
      if (WorldTime != other.WorldTime) return false;
      if (Distance != other.Distance) return false;
      if (RoadTime != other.RoadTime) return false;
      if (Laps != other.Laps) return false;
      if (Speed != other.Speed) return false;
      if (RoadPosition != other.RoadPosition) return false;
      if (CadenceUHz != other.CadenceUHz) return false;
      if (Draft != other.Draft) return false;
      if (Heartrate != other.Heartrate) return false;
      if (Power != other.Power) return false;
      if (Heading != other.Heading) return false;
      if (Lean != other.Lean) return false;
      if (Climbing != other.Climbing) return false;
      if (Time != other.Time) return false;
      if (FrameHue != other.FrameHue) return false;
      if (Flags1 != other.Flags1) return false;
      if (Flags2 != other.Flags2) return false;
      if (Progress != other.Progress) return false;
      if (JoinTime != other.JoinTime) return false;
      if (JustWatching != other.JustWatching) return false;
      if (MwHours != other.MwHours) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(X, other.X)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Z, other.Z)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Y, other.Y)) return false;
      if (WatchingAthleteId != other.WatchingAthleteId) return false;
      if (EventSubgroupId != other.EventSubgroupId) return false;
      if (Sport != other.Sport) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(EventDistance, other.EventDistance)) return false;
      if (CourseId != other.CourseId) return false;
      if (RouteProgress != other.RouteProgress) return false;
      if (RouteRoadIndex != other.RouteRoadIndex) return false;
      if (CanSteer != other.CanSteer) return false;
      if (RouteId != other.RouteId) return false;
      if (PacerBotGroupSize != other.PacerBotGroupSize) return false;
      if (ActiveSteer != other.ActiveSteer) return false;
      if (Portal != other.Portal) return false;
      if (PortalGradientScale != other.PortalGradientScale) return false;
      if (PortalElevationScale != other.PortalElevationScale) return false;
      if (BoostPad != other.BoostPad) return false;
      if (HazardPad != other.HazardPad) return false;
      if (TimeBonus != other.TimeBonus) return false;
      if (RideonBomb != other.RideonBomb) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (AthleteId != 0) hash ^= AthleteId.GetHashCode();
      if (WorldTime != 0UL) hash ^= WorldTime.GetHashCode();
      if (Distance != 0) hash ^= Distance.GetHashCode();
      if (RoadTime != 0) hash ^= RoadTime.GetHashCode();
      if (Laps != 0) hash ^= Laps.GetHashCode();
      if (Speed != 0) hash ^= Speed.GetHashCode();
      if (RoadPosition != 0) hash ^= RoadPosition.GetHashCode();
      if (CadenceUHz != 0) hash ^= CadenceUHz.GetHashCode();
      if (Draft != 0) hash ^= Draft.GetHashCode();
      if (Heartrate != 0) hash ^= Heartrate.GetHashCode();
      if (Power != 0) hash ^= Power.GetHashCode();
      if (Heading != 0) hash ^= Heading.GetHashCode();
      if (Lean != 0) hash ^= Lean.GetHashCode();
      if (Climbing != 0) hash ^= Climbing.GetHashCode();
      if (Time != 0) hash ^= Time.GetHashCode();
      if (FrameHue != 0) hash ^= FrameHue.GetHashCode();
      if (Flags1 != 0) hash ^= Flags1.GetHashCode();
      if (Flags2 != 0) hash ^= Flags2.GetHashCode();
      if (Progress != 0) hash ^= Progress.GetHashCode();
      if (JoinTime != 0L) hash ^= JoinTime.GetHashCode();
      if (JustWatching != false) hash ^= JustWatching.GetHashCode();
      if (MwHours != 0) hash ^= MwHours.GetHashCode();
      if (X != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(X);
      if (Z != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Z);
      if (Y != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Y);
      if (WatchingAthleteId != 0) hash ^= WatchingAthleteId.GetHashCode();
      if (EventSubgroupId != 0) hash ^= EventSubgroupId.GetHashCode();
      if (Sport != global::ZwiftClassLibrary.Sport.Cycling) hash ^= Sport.GetHashCode();
      if (EventDistance != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(EventDistance);
      if (CourseId != 0) hash ^= CourseId.GetHashCode();
      if (RouteProgress != 0) hash ^= RouteProgress.GetHashCode();
      if (RouteRoadIndex != 0) hash ^= RouteRoadIndex.GetHashCode();
      if (CanSteer != false) hash ^= CanSteer.GetHashCode();
      if (RouteId != 0) hash ^= RouteId.GetHashCode();
      if (PacerBotGroupSize != 0) hash ^= PacerBotGroupSize.GetHashCode();
      if (ActiveSteer != false) hash ^= ActiveSteer.GetHashCode();
      if (Portal != false) hash ^= Portal.GetHashCode();
      if (PortalGradientScale != 0) hash ^= PortalGradientScale.GetHashCode();
      if (PortalElevationScale != 0) hash ^= PortalElevationScale.GetHashCode();
      if (BoostPad != 0) hash ^= BoostPad.GetHashCode();
      if (HazardPad != 0) hash ^= HazardPad.GetHashCode();
      if (TimeBonus != 0) hash ^= TimeBonus.GetHashCode();
      if (RideonBomb != 0) hash ^= RideonBomb.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (AthleteId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(AthleteId);
      }
      if (WorldTime != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(WorldTime);
      }
      if (Distance != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Distance);
      }
      if (RoadTime != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(RoadTime);
      }
      if (Laps != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Laps);
      }
      if (Speed != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(Speed);
      }
      if (RoadPosition != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(RoadPosition);
      }
      if (CadenceUHz != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(CadenceUHz);
      }
      if (Draft != 0) {
        output.WriteRawTag(80);
        output.WriteInt32(Draft);
      }
      if (Heartrate != 0) {
        output.WriteRawTag(88);
        output.WriteInt32(Heartrate);
      }
      if (Power != 0) {
        output.WriteRawTag(96);
        output.WriteInt32(Power);
      }
      if (Heading != 0) {
        output.WriteRawTag(104);
        output.WriteInt32(Heading);
      }
      if (Lean != 0) {
        output.WriteRawTag(112);
        output.WriteInt32(Lean);
      }
      if (Climbing != 0) {
        output.WriteRawTag(120);
        output.WriteInt32(Climbing);
      }
      if (Time != 0) {
        output.WriteRawTag(128, 1);
        output.WriteInt32(Time);
      }
      if (FrameHue != 0) {
        output.WriteRawTag(144, 1);
        output.WriteUInt32(FrameHue);
      }
      if (Flags1 != 0) {
        output.WriteRawTag(152, 1);
        output.WriteUInt32(Flags1);
      }
      if (Flags2 != 0) {
        output.WriteRawTag(160, 1);
        output.WriteUInt32(Flags2);
      }
      if (Progress != 0) {
        output.WriteRawTag(168, 1);
        output.WriteUInt32(Progress);
      }
      if (JoinTime != 0L) {
        output.WriteRawTag(176, 1);
        output.WriteInt64(JoinTime);
      }
      if (JustWatching != false) {
        output.WriteRawTag(184, 1);
        output.WriteBool(JustWatching);
      }
      if (MwHours != 0) {
        output.WriteRawTag(192, 1);
        output.WriteInt32(MwHours);
      }
      if (X != 0F) {
        output.WriteRawTag(205, 1);
        output.WriteFloat(X);
      }
      if (Z != 0F) {
        output.WriteRawTag(213, 1);
        output.WriteFloat(Z);
      }
      if (Y != 0F) {
        output.WriteRawTag(221, 1);
        output.WriteFloat(Y);
      }
      if (WatchingAthleteId != 0) {
        output.WriteRawTag(224, 1);
        output.WriteInt32(WatchingAthleteId);
      }
      if (EventSubgroupId != 0) {
        output.WriteRawTag(232, 1);
        output.WriteInt32(EventSubgroupId);
      }
      if (Sport != global::ZwiftClassLibrary.Sport.Cycling) {
        output.WriteRawTag(248, 1);
        output.WriteEnum((int) Sport);
      }
      if (EventDistance != 0F) {
        output.WriteRawTag(149, 2);
        output.WriteFloat(EventDistance);
      }
      if (CourseId != 0) {
        output.WriteRawTag(152, 2);
        output.WriteInt32(CourseId);
      }
      if (RouteProgress != 0) {
        output.WriteRawTag(160, 2);
        output.WriteInt32(RouteProgress);
      }
      if (RouteRoadIndex != 0) {
        output.WriteRawTag(168, 2);
        output.WriteInt32(RouteRoadIndex);
      }
      if (CanSteer != false) {
        output.WriteRawTag(176, 2);
        output.WriteBool(CanSteer);
      }
      if (RouteId != 0) {
        output.WriteRawTag(184, 2);
        output.WriteUInt32(RouteId);
      }
      if (PacerBotGroupSize != 0) {
        output.WriteRawTag(192, 2);
        output.WriteInt32(PacerBotGroupSize);
      }
      if (ActiveSteer != false) {
        output.WriteRawTag(200, 2);
        output.WriteBool(ActiveSteer);
      }
      if (Portal != false) {
        output.WriteRawTag(216, 2);
        output.WriteBool(Portal);
      }
      if (PortalGradientScale != 0) {
        output.WriteRawTag(224, 2);
        output.WriteInt32(PortalGradientScale);
      }
      if (PortalElevationScale != 0) {
        output.WriteRawTag(232, 2);
        output.WriteInt32(PortalElevationScale);
      }
      if (BoostPad != 0) {
        output.WriteRawTag(240, 2);
        output.WriteInt32(BoostPad);
      }
      if (HazardPad != 0) {
        output.WriteRawTag(248, 2);
        output.WriteInt32(HazardPad);
      }
      if (TimeBonus != 0) {
        output.WriteRawTag(128, 3);
        output.WriteInt32(TimeBonus);
      }
      if (RideonBomb != 0) {
        output.WriteRawTag(136, 3);
        output.WriteInt32(RideonBomb);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (AthleteId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(AthleteId);
      }
      if (WorldTime != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(WorldTime);
      }
      if (Distance != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Distance);
      }
      if (RoadTime != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(RoadTime);
      }
      if (Laps != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Laps);
      }
      if (Speed != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(Speed);
      }
      if (RoadPosition != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(RoadPosition);
      }
      if (CadenceUHz != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(CadenceUHz);
      }
      if (Draft != 0) {
        output.WriteRawTag(80);
        output.WriteInt32(Draft);
      }
      if (Heartrate != 0) {
        output.WriteRawTag(88);
        output.WriteInt32(Heartrate);
      }
      if (Power != 0) {
        output.WriteRawTag(96);
        output.WriteInt32(Power);
      }
      if (Heading != 0) {
        output.WriteRawTag(104);
        output.WriteInt32(Heading);
      }
      if (Lean != 0) {
        output.WriteRawTag(112);
        output.WriteInt32(Lean);
      }
      if (Climbing != 0) {
        output.WriteRawTag(120);
        output.WriteInt32(Climbing);
      }
      if (Time != 0) {
        output.WriteRawTag(128, 1);
        output.WriteInt32(Time);
      }
      if (FrameHue != 0) {
        output.WriteRawTag(144, 1);
        output.WriteUInt32(FrameHue);
      }
      if (Flags1 != 0) {
        output.WriteRawTag(152, 1);
        output.WriteUInt32(Flags1);
      }
      if (Flags2 != 0) {
        output.WriteRawTag(160, 1);
        output.WriteUInt32(Flags2);
      }
      if (Progress != 0) {
        output.WriteRawTag(168, 1);
        output.WriteUInt32(Progress);
      }
      if (JoinTime != 0L) {
        output.WriteRawTag(176, 1);
        output.WriteInt64(JoinTime);
      }
      if (JustWatching != false) {
        output.WriteRawTag(184, 1);
        output.WriteBool(JustWatching);
      }
      if (MwHours != 0) {
        output.WriteRawTag(192, 1);
        output.WriteInt32(MwHours);
      }
      if (X != 0F) {
        output.WriteRawTag(205, 1);
        output.WriteFloat(X);
      }
      if (Z != 0F) {
        output.WriteRawTag(213, 1);
        output.WriteFloat(Z);
      }
      if (Y != 0F) {
        output.WriteRawTag(221, 1);
        output.WriteFloat(Y);
      }
      if (WatchingAthleteId != 0) {
        output.WriteRawTag(224, 1);
        output.WriteInt32(WatchingAthleteId);
      }
      if (EventSubgroupId != 0) {
        output.WriteRawTag(232, 1);
        output.WriteInt32(EventSubgroupId);
      }
      if (Sport != global::ZwiftClassLibrary.Sport.Cycling) {
        output.WriteRawTag(248, 1);
        output.WriteEnum((int) Sport);
      }
      if (EventDistance != 0F) {
        output.WriteRawTag(149, 2);
        output.WriteFloat(EventDistance);
      }
      if (CourseId != 0) {
        output.WriteRawTag(152, 2);
        output.WriteInt32(CourseId);
      }
      if (RouteProgress != 0) {
        output.WriteRawTag(160, 2);
        output.WriteInt32(RouteProgress);
      }
      if (RouteRoadIndex != 0) {
        output.WriteRawTag(168, 2);
        output.WriteInt32(RouteRoadIndex);
      }
      if (CanSteer != false) {
        output.WriteRawTag(176, 2);
        output.WriteBool(CanSteer);
      }
      if (RouteId != 0) {
        output.WriteRawTag(184, 2);
        output.WriteUInt32(RouteId);
      }
      if (PacerBotGroupSize != 0) {
        output.WriteRawTag(192, 2);
        output.WriteInt32(PacerBotGroupSize);
      }
      if (ActiveSteer != false) {
        output.WriteRawTag(200, 2);
        output.WriteBool(ActiveSteer);
      }
      if (Portal != false) {
        output.WriteRawTag(216, 2);
        output.WriteBool(Portal);
      }
      if (PortalGradientScale != 0) {
        output.WriteRawTag(224, 2);
        output.WriteInt32(PortalGradientScale);
      }
      if (PortalElevationScale != 0) {
        output.WriteRawTag(232, 2);
        output.WriteInt32(PortalElevationScale);
      }
      if (BoostPad != 0) {
        output.WriteRawTag(240, 2);
        output.WriteInt32(BoostPad);
      }
      if (HazardPad != 0) {
        output.WriteRawTag(248, 2);
        output.WriteInt32(HazardPad);
      }
      if (TimeBonus != 0) {
        output.WriteRawTag(128, 3);
        output.WriteInt32(TimeBonus);
      }
      if (RideonBomb != 0) {
        output.WriteRawTag(136, 3);
        output.WriteInt32(RideonBomb);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (AthleteId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(AthleteId);
      }
      if (WorldTime != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(WorldTime);
      }
      if (Distance != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Distance);
      }
      if (RoadTime != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RoadTime);
      }
      if (Laps != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Laps);
      }
      if (Speed != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Speed);
      }
      if (RoadPosition != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RoadPosition);
      }
      if (CadenceUHz != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CadenceUHz);
      }
      if (Draft != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Draft);
      }
      if (Heartrate != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Heartrate);
      }
      if (Power != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Power);
      }
      if (Heading != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Heading);
      }
      if (Lean != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Lean);
      }
      if (Climbing != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Climbing);
      }
      if (Time != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(Time);
      }
      if (FrameHue != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(FrameHue);
      }
      if (Flags1 != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(Flags1);
      }
      if (Flags2 != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(Flags2);
      }
      if (Progress != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(Progress);
      }
      if (JoinTime != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(JoinTime);
      }
      if (JustWatching != false) {
        size += 2 + 1;
      }
      if (MwHours != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(MwHours);
      }
      if (X != 0F) {
        size += 2 + 4;
      }
      if (Z != 0F) {
        size += 2 + 4;
      }
      if (Y != 0F) {
        size += 2 + 4;
      }
      if (WatchingAthleteId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(WatchingAthleteId);
      }
      if (EventSubgroupId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(EventSubgroupId);
      }
      if (Sport != global::ZwiftClassLibrary.Sport.Cycling) {
        size += 2 + pb::CodedOutputStream.ComputeEnumSize((int) Sport);
      }
      if (EventDistance != 0F) {
        size += 2 + 4;
      }
      if (CourseId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(CourseId);
      }
      if (RouteProgress != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RouteProgress);
      }
      if (RouteRoadIndex != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RouteRoadIndex);
      }
      if (CanSteer != false) {
        size += 2 + 1;
      }
      if (RouteId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(RouteId);
      }
      if (PacerBotGroupSize != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(PacerBotGroupSize);
      }
      if (ActiveSteer != false) {
        size += 2 + 1;
      }
      if (Portal != false) {
        size += 2 + 1;
      }
      if (PortalGradientScale != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(PortalGradientScale);
      }
      if (PortalElevationScale != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(PortalElevationScale);
      }
      if (BoostPad != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(BoostPad);
      }
      if (HazardPad != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(HazardPad);
      }
      if (TimeBonus != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(TimeBonus);
      }
      if (RideonBomb != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RideonBomb);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PlayerState other) {
      if (other == null) {
        return;
      }
      if (other.AthleteId != 0) {
        AthleteId = other.AthleteId;
      }
      if (other.WorldTime != 0UL) {
        WorldTime = other.WorldTime;
      }
      if (other.Distance != 0) {
        Distance = other.Distance;
      }
      if (other.RoadTime != 0) {
        RoadTime = other.RoadTime;
      }
      if (other.Laps != 0) {
        Laps = other.Laps;
      }
      if (other.Speed != 0) {
        Speed = other.Speed;
      }
      if (other.RoadPosition != 0) {
        RoadPosition = other.RoadPosition;
      }
      if (other.CadenceUHz != 0) {
        CadenceUHz = other.CadenceUHz;
      }
      if (other.Draft != 0) {
        Draft = other.Draft;
      }
      if (other.Heartrate != 0) {
        Heartrate = other.Heartrate;
      }
      if (other.Power != 0) {
        Power = other.Power;
      }
      if (other.Heading != 0) {
        Heading = other.Heading;
      }
      if (other.Lean != 0) {
        Lean = other.Lean;
      }
      if (other.Climbing != 0) {
        Climbing = other.Climbing;
      }
      if (other.Time != 0) {
        Time = other.Time;
      }
      if (other.FrameHue != 0) {
        FrameHue = other.FrameHue;
      }
      if (other.Flags1 != 0) {
        Flags1 = other.Flags1;
      }
      if (other.Flags2 != 0) {
        Flags2 = other.Flags2;
      }
      if (other.Progress != 0) {
        Progress = other.Progress;
      }
      if (other.JoinTime != 0L) {
        JoinTime = other.JoinTime;
      }
      if (other.JustWatching != false) {
        JustWatching = other.JustWatching;
      }
      if (other.MwHours != 0) {
        MwHours = other.MwHours;
      }
      if (other.X != 0F) {
        X = other.X;
      }
      if (other.Z != 0F) {
        Z = other.Z;
      }
      if (other.Y != 0F) {
        Y = other.Y;
      }
      if (other.WatchingAthleteId != 0) {
        WatchingAthleteId = other.WatchingAthleteId;
      }
      if (other.EventSubgroupId != 0) {
        EventSubgroupId = other.EventSubgroupId;
      }
      if (other.Sport != global::ZwiftClassLibrary.Sport.Cycling) {
        Sport = other.Sport;
      }
      if (other.EventDistance != 0F) {
        EventDistance = other.EventDistance;
      }
      if (other.CourseId != 0) {
        CourseId = other.CourseId;
      }
      if (other.RouteProgress != 0) {
        RouteProgress = other.RouteProgress;
      }
      if (other.RouteRoadIndex != 0) {
        RouteRoadIndex = other.RouteRoadIndex;
      }
      if (other.CanSteer != false) {
        CanSteer = other.CanSteer;
      }
      if (other.RouteId != 0) {
        RouteId = other.RouteId;
      }
      if (other.PacerBotGroupSize != 0) {
        PacerBotGroupSize = other.PacerBotGroupSize;
      }
      if (other.ActiveSteer != false) {
        ActiveSteer = other.ActiveSteer;
      }
      if (other.Portal != false) {
        Portal = other.Portal;
      }
      if (other.PortalGradientScale != 0) {
        PortalGradientScale = other.PortalGradientScale;
      }
      if (other.PortalElevationScale != 0) {
        PortalElevationScale = other.PortalElevationScale;
      }
      if (other.BoostPad != 0) {
        BoostPad = other.BoostPad;
      }
      if (other.HazardPad != 0) {
        HazardPad = other.HazardPad;
      }
      if (other.TimeBonus != 0) {
        TimeBonus = other.TimeBonus;
      }
      if (other.RideonBomb != 0) {
        RideonBomb = other.RideonBomb;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            AthleteId = input.ReadInt32();
            break;
          }
          case 16: {
            WorldTime = input.ReadUInt64();
            break;
          }
          case 24: {
            Distance = input.ReadInt32();
            break;
          }
          case 32: {
            RoadTime = input.ReadInt32();
            break;
          }
          case 40: {
            Laps = input.ReadInt32();
            break;
          }
          case 48: {
            Speed = input.ReadInt32();
            break;
          }
          case 64: {
            RoadPosition = input.ReadInt32();
            break;
          }
          case 72: {
            CadenceUHz = input.ReadInt32();
            break;
          }
          case 80: {
            Draft = input.ReadInt32();
            break;
          }
          case 88: {
            Heartrate = input.ReadInt32();
            break;
          }
          case 96: {
            Power = input.ReadInt32();
            break;
          }
          case 104: {
            Heading = input.ReadInt32();
            break;
          }
          case 112: {
            Lean = input.ReadInt32();
            break;
          }
          case 120: {
            Climbing = input.ReadInt32();
            break;
          }
          case 128: {
            Time = input.ReadInt32();
            break;
          }
          case 144: {
            FrameHue = input.ReadUInt32();
            break;
          }
          case 152: {
            Flags1 = input.ReadUInt32();
            break;
          }
          case 160: {
            Flags2 = input.ReadUInt32();
            break;
          }
          case 168: {
            Progress = input.ReadUInt32();
            break;
          }
          case 176: {
            JoinTime = input.ReadInt64();
            break;
          }
          case 184: {
            JustWatching = input.ReadBool();
            break;
          }
          case 192: {
            MwHours = input.ReadInt32();
            break;
          }
          case 205: {
            X = input.ReadFloat();
            break;
          }
          case 213: {
            Z = input.ReadFloat();
            break;
          }
          case 221: {
            Y = input.ReadFloat();
            break;
          }
          case 224: {
            WatchingAthleteId = input.ReadInt32();
            break;
          }
          case 232: {
            EventSubgroupId = input.ReadInt32();
            break;
          }
          case 248: {
            Sport = (global::ZwiftClassLibrary.Sport) input.ReadEnum();
            break;
          }
          case 277: {
            EventDistance = input.ReadFloat();
            break;
          }
          case 280: {
            CourseId = input.ReadInt32();
            break;
          }
          case 288: {
            RouteProgress = input.ReadInt32();
            break;
          }
          case 296: {
            RouteRoadIndex = input.ReadInt32();
            break;
          }
          case 304: {
            CanSteer = input.ReadBool();
            break;
          }
          case 312: {
            RouteId = input.ReadUInt32();
            break;
          }
          case 320: {
            PacerBotGroupSize = input.ReadInt32();
            break;
          }
          case 328: {
            ActiveSteer = input.ReadBool();
            break;
          }
          case 344: {
            Portal = input.ReadBool();
            break;
          }
          case 352: {
            PortalGradientScale = input.ReadInt32();
            break;
          }
          case 360: {
            PortalElevationScale = input.ReadInt32();
            break;
          }
          case 368: {
            BoostPad = input.ReadInt32();
            break;
          }
          case 376: {
            HazardPad = input.ReadInt32();
            break;
          }
          case 384: {
            TimeBonus = input.ReadInt32();
            break;
          }
          case 392: {
            RideonBomb = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            AthleteId = input.ReadInt32();
            break;
          }
          case 16: {
            WorldTime = input.ReadUInt64();
            break;
          }
          case 24: {
            Distance = input.ReadInt32();
            break;
          }
          case 32: {
            RoadTime = input.ReadInt32();
            break;
          }
          case 40: {
            Laps = input.ReadInt32();
            break;
          }
          case 48: {
            Speed = input.ReadInt32();
            break;
          }
          case 64: {
            RoadPosition = input.ReadInt32();
            break;
          }
          case 72: {
            CadenceUHz = input.ReadInt32();
            break;
          }
          case 80: {
            Draft = input.ReadInt32();
            break;
          }
          case 88: {
            Heartrate = input.ReadInt32();
            break;
          }
          case 96: {
            Power = input.ReadInt32();
            break;
          }
          case 104: {
            Heading = input.ReadInt32();
            break;
          }
          case 112: {
            Lean = input.ReadInt32();
            break;
          }
          case 120: {
            Climbing = input.ReadInt32();
            break;
          }
          case 128: {
            Time = input.ReadInt32();
            break;
          }
          case 144: {
            FrameHue = input.ReadUInt32();
            break;
          }
          case 152: {
            Flags1 = input.ReadUInt32();
            break;
          }
          case 160: {
            Flags2 = input.ReadUInt32();
            break;
          }
          case 168: {
            Progress = input.ReadUInt32();
            break;
          }
          case 176: {
            JoinTime = input.ReadInt64();
            break;
          }
          case 184: {
            JustWatching = input.ReadBool();
            break;
          }
          case 192: {
            MwHours = input.ReadInt32();
            break;
          }
          case 205: {
            X = input.ReadFloat();
            break;
          }
          case 213: {
            Z = input.ReadFloat();
            break;
          }
          case 221: {
            Y = input.ReadFloat();
            break;
          }
          case 224: {
            WatchingAthleteId = input.ReadInt32();
            break;
          }
          case 232: {
            EventSubgroupId = input.ReadInt32();
            break;
          }
          case 248: {
            Sport = (global::ZwiftClassLibrary.Sport) input.ReadEnum();
            break;
          }
          case 277: {
            EventDistance = input.ReadFloat();
            break;
          }
          case 280: {
            CourseId = input.ReadInt32();
            break;
          }
          case 288: {
            RouteProgress = input.ReadInt32();
            break;
          }
          case 296: {
            RouteRoadIndex = input.ReadInt32();
            break;
          }
          case 304: {
            CanSteer = input.ReadBool();
            break;
          }
          case 312: {
            RouteId = input.ReadUInt32();
            break;
          }
          case 320: {
            PacerBotGroupSize = input.ReadInt32();
            break;
          }
          case 328: {
            ActiveSteer = input.ReadBool();
            break;
          }
          case 344: {
            Portal = input.ReadBool();
            break;
          }
          case 352: {
            PortalGradientScale = input.ReadInt32();
            break;
          }
          case 360: {
            PortalElevationScale = input.ReadInt32();
            break;
          }
          case 368: {
            BoostPad = input.ReadInt32();
            break;
          }
          case 376: {
            HazardPad = input.ReadInt32();
            break;
          }
          case 384: {
            TimeBonus = input.ReadInt32();
            break;
          }
          case 392: {
            RideonBomb = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
